name=ALS_PT19
version=1.0.0
author=Nicholas Limparis (Snoozebot3000)
maintainer=Nicholas Limparis (Snoozebot3000) <github.com/Snoozebot3000>
sentence=A fast, memory-efficient library for the Everlight ALS-PT19 ambient light sensor.
paragraph=This library uses optimized PROGMEM lookup tables and linear interpolation to convert raw ADC readings into accurate LUX values. It features compile-time selection for Fluorescent vs. Incandescent lighting environments and supports custom load resistor calibration.
category=Sensors
url=https://github.com/Snoozebot3000/ALS_PT19
architectures=*
includes=ALS_PT19.h